### ISSUE TITLE
Todo Phase 2

### ISSUE THREAD

**Issue by puguhsudarma** [puguhsudarma/expo-nearby-connections#5]
- [ ] 1. Create permission handler
- [ ] 2. Create React Provider and Hooks module
- [ ] 3. Add new "additionalInfo" parameter
- [ ] 4. Create CI/CD to publish to npm
- [ ] 5. Publish to JSR Deno
